run_scraping:
    UV_ENV_FILE=.env uv run scrape.py

generate_summaries:
    UV_ENV_FILE=.env uv run analyze.py

run_scoring:
     UV_ENV_FILE=.env uv run score.py

run_matching:
    UV_ENV_FILE=.env uv run matcher.py
